"""
This program contains all the important path names and parameters.
We only need to change them here if necessary and the changes will be applied to all files.

Author: Siqi Dai
"""


folder = "experiment/Hongqi/"

# pathname of the txt file that stores the ip addresses of four cameras
# 相机IP地址txt文件
cam_ip_txt = folder + "cam_ip.txt"

# pathnames of txt files with 3D coords of points on the standard car image (generated by GUI_Extract3DCoordinates.py)
# 汽车基准位置车身特征点的三维世界坐标 (通过GUI_Extract3DCoordinates.py生成)
coordinates3D_std_left = folder + "extract3D_left.txt"
coordinates3D_std_left2 = folder + "extract3D_left2.txt"
coordinates3D_std_right = folder + "extract3D_right.txt"
coordinates3D_std_right2 = folder + "extract3D_right2.txt"

# paths of calibration images (chessboard)
# 棋盘格标定板图片路径
left_clb = folder + "calib_left/"
left2_clb = folder + "calib_left2/"
right_clb = folder + "calib_right/"
right2_clb = folder + "calib_right2/"

# the following four are paths of car images
# 汽车图片路径
left_car = folder + "car_left/"
left2_car = folder + "car_left2/"
right_car = folder + "car_right/"
right2_car = folder + "car_right2/"

fn_std = '1.bmp'  # filename of the standard image （car at base position）汽车基准位置图片名
fn_new = '3.bmp'  # filename of the new image （car at new position）汽车非基准位置图片名

# distance from the origin on the car to the rotary center of the multi-axes stage
# 汽车上的原点到云台旋转轴的距离
offset = (0, 0, 0)  # for Demo's car model：-36.3, 20, 19-60+190

# model information
# CAD模型上的特征点数量
num_points_model_bottom = 0  # total number of points on the bottom of the CAD model (0.bmp) 汽车CAD模型上底板特征点数量
num_points_model_left = 35  # total number of points on the left side of the CAD model (1.bmp) 汽车CAD模型上左侧面特征点数量
num_points_model_right = 35  # total number of points on the right side of the CAD model (2.bmp) 汽车CAD模型上右侧面特征点数量

# camera information
# 相机分辨率
cam_width = 1296
cam_height = 972

# minimum and maximum areas of detected feature points
# 被检测圆斑的面积大小（这将影响检测到的特征点数量，检测到的点越多，程序运行越慢。）
min_area = 100
max_area = 200

# port names for the light
# 光源串口名 (光源连接在电脑上后，查看端口名称)
light_port1 = 'COM3'
light_port2 = 'COM4'
